### ISSUE TITLE
cannot logout after sign up

### ISSUE THREAD

**Issue by cheezafizz** [swsnu/swpp2020-team15#57]
The following is the scenario of the error

1. User signs up,  creating his/her ID
2. User gets logged in automatically after his/her signup
3. User wants to logout for now
4. But he/she can't logout, getting  401 unauthorized error from server.

**Comment by lgm0905** [comment]
Resolved.

First, `signup` feature kept the tone of `log-in` straight.
The problem was that the login status on the backend was not reflected because the `dispatch` was not performed.
In addition, the `email`, `nickname` unique check was not issued in `signup`, `mypage-myinfo` page, and this problem was solved by expanding the already implemented `api/users/duplicate` api.
