### ISSUE TITLE
Default group should not be deleted

### ISSUE THREAD

**Issue by cheezafizz** [swsnu/swpp2020-team15#84]
![image](https://user-images.githubusercontent.com/54826729/101292774-eb3d3f00-3854-11eb-95df-648370ad20ba.png)

~~User would be better informed when it contains some descriptions when there aren't any groups, such as~~
~~"There are no groups, add a group first"~~

Default group should not be deletedDefault group should not be deleted

**Comment by lgm0905** [comment]
I implemented this problem with user can deleting default group,

The reason is following.
  * User can be disturbed with limiting user's behavior.
  * When user create same name with default group, we have to write more BE codes that checks which is default group
  * Or, we have to save id of default group.

It is temporarily, so we need to discuss about it and determine which one is better.
